dist: trusty
language: rust
services:
  - zookeeper
rust:
  - nightly
cache: cargo
env:
  - SETTLE_TIME=2000
script:
  - cargo check --all --all-targets
  - RUST_BACKTRACE=full cargo test --verbose --all
addons:
  apt:
    packages:
    - libhwloc-dev
    - zookeeper
